name: Pressure Monitor Django App

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: pressure_monitor
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/prod.txt
        pip install -r requirements/test.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics --verbose
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        plugins: "flake8-commas flake8-quotes"
    - name: Run tests
      run: python manage.py test
